# Generated by Django 2.2 on 2020-06-16 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200616_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='COBBikesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.SlugField(default='', max_length=10)),
                ('price', models.SlugField(default='Rs 0 per KM', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='COBScooterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scooter_category_name', models.SlugField(default='', max_length=10)),
                ('price', models.SlugField(default='Rs 0 per KM', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='COBScooterName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scooter_name', models.SlugField(default='', max_length=100)),
                ('scooter_category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.COBScooterCategory')),
            ],
        ),
        migrations.CreateModel(
            name='COBBikesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_name', models.SlugField(default='', max_length=100)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.COBBikesCategory')),
            ],
        ),
    ]
