# Generated by Django 2.2 on 2020-06-18 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_cobbikescategory_cobbikesdata_cobscootercategory_cobscootername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobbikesdata',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='cobscootername',
            name='scooter_category_name',
        ),
        migrations.DeleteModel(
            name='COBBikesCategory',
        ),
        migrations.DeleteModel(
            name='COBBikesData',
        ),
        migrations.DeleteModel(
            name='COBScooterCategory',
        ),
        migrations.DeleteModel(
            name='COBScooterName',
        ),
    ]
