# Generated by Django 2.2 on 2020-06-16 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_bikeprofile_scooterprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BikeProfile',
        ),
    ]
