# Generated by Django 2.2 on 2020-06-16 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_delete_bikeprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScooterProfile',
        ),
    ]
