# Generated by Django 2.2 on 2020-06-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0004_delete_scooterprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobbikesdata',
            name='bike_image',
            field=models.ImageField(default='default.png', upload_to='bike_pics'),
        ),
        migrations.AddField(
            model_name='cobscootername',
            name='scooter_image',
            field=models.ImageField(default='default.png', upload_to='scooter_pics'),
        ),
    ]
