# Generated by Django 2.2 on 2020-06-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0005_auto_20200617_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.SlugField(default='', max_length=100)),
                ('date_booked', models.DateField(auto_now_add=True)),
                ('return_time', models.TimeField()),
                ('destination', models.SlugField(max_length=200)),
            ],
        ),
    ]
