# Generated by Django 2.2 on 2020-06-18 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0006_bookingdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingdetails',
            old_name='date_booked',
            new_name='booked_date',
        ),
        migrations.RemoveField(
            model_name='bookingdetails',
            name='vehicle_name',
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='pickup_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='destination',
            field=models.TextField(db_column='address', default='', max_length=300),
        ),
    ]
