# Generated by Django 2.2 on 2020-06-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0007_auto_20200618_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobbikesdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cobscootername',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
