# Generated by Django 2.2 on 2020-06-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0010_auto_20200624_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='booking_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
