# Generated by Django 2.2 on 2020-06-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0011_auto_20200624_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetails',
            name='booking_date',
        ),
    ]
