# Generated by Django 2.2 on 2020-06-16 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cobvehicles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='COBVehicles',
        ),
    ]
